function [yes,ms] = FauxPasQuestion1(constants)

yes = 0;
no = 0;
ms = 0;

question = constants(1);
question = sprintf(['QUESTION\n\n', question{1}]);
t0 = clock;
ScrSize = get(0,'ScreenSize');
uicontrol('Style', 'text','fontsize',30,'BackgroundColor','w', ...
        'String', question,'Units','normalized','Position', [0 0 1 1]); 
S.pb = uicontrol('style','push',...
                 'unit','normalized',...
                 'BackgroundColor','k', ...
                 'ForegroundColor', 'w',...
                 'fontsize',30, ...
                 'position',[.1 .1 .2 .2],...
                 'string','Yes','callback',{@pb_call});
S.pf = uicontrol('style','pushbutton',...
                 'unit','normalized',...
                 'BackgroundColor','k', ...
                 'ForegroundColor', 'w',...
                 'fontsize',30, ...
                 'position',[.7 .1 .2 .2],...
                 'string','No','callback',{@pb_call}); 
while true & ~isempty(findall(0,'Type','Figure'))
    pause(.1)
    if yes || no
        break
    end
end
    
function pb_call(hObject,eventdata)    
    yes = get(S.pb(1),'val');
    no = get(S.pf(1),'val'); 
    ms = round(etime(clock,t0) * 1000);
end


end