function output = MindVoicefigureText(byte)

files = [1,2,3,4,5,8,9,10,11,12,14,15,16,17,18,20,21,24,25,27,28,30,32,33,37];

answers = {'Defiant' 'Alarmed' 'Earnest' 'Convinced'; ...
    'Surprised' 'Grateful' 'Friendly' 'Interested'; ...
    'Desperate' 'Confused' 'Threatening' 'Angry'; ...
    'Frustrated' 'Suspicious' 'Intrigued' 'Doubtful' ;...
    'Worried' 'Shy' 'Upset' 'Insulted' ;...
    'Concerned' 'Apologetic' 'Dazed' 'Hurried' ;...
    'Despairing' 'Pleading' 'Assertive' 'Horrified' ;...
    'Perplexed' 'Awe' 'Accusatory' 'Lured' ;...
    'Assured' 'Nervous' 'Puzzled' 'Serious' ;...
    'Bossy' 'Irritated' 'Cruel' 'Surprised' ;...
    'Joyous' 'Scared' 'Playful' 'Desperate' ;...
    'Decided' 'Embarrassed' 'Unsure' 'Furious' ;...
    'Terrified' 'Broken' 'Frustrated' 'Angry' ;...
    'Arrogant' 'Enraged' 'Appalled' 'Scared' ;...
    'Disappointed' 'Unsure' 'Apologetic' 'Tearful' ;...
    'Impatient' 'Admiring' 'Bitter' 'Sincere' ;...
    'Melancholy' 'Ambivalent' 'Aggrieved' 'Resolved' ;...
    'Relaxed' 'Displeased' 'Competitive' 'Concerned' ;...
    'Deceitful' 'Menacing' 'Determined' 'Sincere' ;...
    'Angry' 'Derogatory' 'Resentful' 'Nostalgic' ;...
    'Stern' 'Oppressive' 'Curious' 'Complacent' ;...
    'Unconcerned' 'Joking' 'Defensive' 'Indignant' ;...
    'Impatient' 'Insulted' 'Disappointed' 'Curious' ;...
    'Pitying' 'Brooding' 'Irritated' 'Resigned' ;...
    'Bossy' 'Fond' 'Hopeful' 'Irritated'};

[tf, index] = ismember(byte, files);
output = answers(index,:);

end